### ISSUE TITLE
Python syntax-highlighting

### ISSUE THREAD

**Issue by mariush2** [kaicataldo/material.vim#15]
Hi,
My python syntax highlighting is not working as I expected. Not entirely sure if that is an issue with this theme or my vim configuration. I am currently using [vim-polyglot](https://github.com/sheerun/vim-polyglot) and this theme. Here is a screenshot showing that the syntax is not being highlighted:

<img width="799" alt="Screenshot 2019-03-24 at 11 02 54" src="https://user-images.githubusercontent.com/24507952/54877831-6a41d800-4e24-11e9-9e0e-bf56263063e9.png">

As you can see there is almost no hightlighting.

If this is a case of this theme not having python language support, I'd be more than happy to make one.

Just to showcase it working in JS here is another screenshot:

<img width="937" alt="Screenshot 2019-03-24 at 11 06 25" src="https://user-images.githubusercontent.com/24507952/54877884-e3412f80-4e24-11e9-9c05-6ee5c86aa94f.png">

**Comment by kaicataldo** [comment]
Hey, thanks for the issue. You're correct - there aren't any specific colors set for any Python syntax plugins. I'm mostly a JS dev, which is why there's a lot of customization there. 

PRs are welcome! I would just want to make sure we're adding colors for a popular syntax plugin. You can see an example of the JS colors [here](https://github.com/kaicataldo/material.vim/blob/master/colors/material.vim#L160).

**Comment by mariush2** [comment]
I see, Vim-polyglot has ~2500 stars on their github repo. Do I start adding highlighting for python uses that syntax plugin?

**Comment by kaicataldo** [comment]
It looks like vim-polyglot uses [this syntax plugin](https://github.com/vim-python/python-syntax).

**Comment by mariush2** [comment]
I have started writing the colors for python now.

**Comment by ashwinvis** [comment]
I am quite happy with the syntax highlighting for Python now. @mariush2, you had used a very bare script for comparison. See instead:

```python
import unittest
import os


class TestFile(unittest.TestCase):

    def setUp(self):
        self.file = open("test_file.txt", "w")

    def tearDown(self):
        os.remove("test_file.txt")

    def test_meh(self):
        self.file.write("manga")


if __name__ == "__main__":
    unittest.main()
```

![Screenshot_20190404_110447](https://user-images.githubusercontent.com/9155111/55543863-6da55100-56b9-11e9-9b4b-51b99d2a59d6.png)

**Comment by mariush2** [comment]
Oh, yeah that looks way better than what I have on my computer. I have no idea why mine looks like it does. I have configured my colorscheme such: `colorscheme material`. I also use vim-polyglot as mentioned earlier in the thread. Another thing to note is that I have this `let g:python_highlight_all=1` in my .vimrc.

Here is a screenshot with the same code you showed:

<img width="473" alt="Screenshot 2019-04-04 at 11 17 16" src="https://user-images.githubusercontent.com/24507952/55544526-90d8fc00-56cb-11e9-86e8-4839d75a7993.png">

**Comment by mariush2** [comment]
To clarify what I want to achieve with the new highlighting for python.

Here is a screenshot of some code in vim:

<img width="664" alt="Screenshot 2019-04-04 at 11 25 05" src="https://user-images.githubusercontent.com/24507952/55544939-70f60800-56cc-11e9-8104-4f8922f5fd97.png">

Here is the same piece of code in Atom using the material theme:

<img width="732" alt="Screenshot 2019-04-04 at 11 25 30" src="https://user-images.githubusercontent.com/24507952/55544960-7d7a6080-56cc-11e9-8298-eabd34dedf6c.png">


I want to get closer to the Atom look in vim here. Specifically on lines like `request.session['login'] = True` and `user = authenticate(username=form.username, password=form.password)`

**Comment by ashwinvis** [comment]
Just my opinion, take it as constructive feedback:
* Overall I feel the vim version is easier to read
* :+1:  for colouring methods (`is_valid`) and classes / functions (`LoginForm`, `redirect`) in blue and keyword args (`commit=`, `username=`) in cyan  - it might be possible to do that in vim, and maybe it helps
* :-1: However, I don't like how the color of the variable `request`, `form`, `user` etc change between based on context. It is distracting.

**Comment by kaicataldo** [comment]
I'm definitely open to adding some Python-specific syntax highlighting. I'd love to try to keep colors consistent between languages where we can, but that's obviously not possible 100% of the time. If someone does decide to take this on, if we could use the JS example provided by the issue author as a guide, I think we'll be on the right track.

**Comment by kaicataldo** [comment]
Closing this due to lack of movement. Comment above still stands and would definitely be open to updating styles. :)
