### ISSUE TITLE
Palenight lightline and cursor line

### ISSUE THREAD

**Issue by skbolton** [kaicataldo/material.vim#18]
First off great theme really liking being able to go between the material themes and get the sublime text material theme look.

I was going to adjust the cursorline and the lightline theme personally though. For me the backing color is a little too close to what the default theme color palette is. Wanted to see if you at all agreed and wanted a PR to change it closer to how palenight.vim has it.

Thanks again

**Comment by kaicataldo** [comment]
Hey, mind sharing a screenshot of what you're proposing? It'll make it easier to make a decision then. Thanks!

**Comment by skbolton** [comment]
So here is how vscode palenight shows the cursor line. Notice the darker background <img width="1279" alt="Screen Shot 2019-04-24 at 12 31 01 AM" src="https://user-images.githubusercontent.com/13260877/56637296-85248980-6628-11e9-9694-8d215fd7dc9b.png">

And here is how the palenight.vim cursor line looks, little lighter than vscode but still dark.
<img width="856" alt="Screen Shot 2019-04-24 at 12 31 31 AM" src="https://user-images.githubusercontent.com/13260877/56637343-a84f3900-6628-11e9-9c7d-394fe868edc8.png">

and here is this repo's cursor line. To me it looks the like the same green as the default color
<img width="821" alt="Screen Shot 2019-04-24 at 12 34 21 AM" src="https://user-images.githubusercontent.com/13260877/56637404-d6347d80-6628-11e9-9fb3-35d1f0983630.png">

I can make edits and post a photo of the changes in this repo. But roughly what I was proposing was to move away from the greenish color and do a darker than the background color. 

Love it? Hate it?

**Comment by kaicataldo** [comment]
That definitely looks like an improvement to me. I'd love to match the official VS Code version where possible :)

One thing to note is that [this uses](https://github.com/kaicataldo/material.vim/blob/master/colors/material.vim#L62) one of the [predefined colors](https://github.com/kaicataldo/material.vim/blob/master/colors/material.vim#L28). I wonder if the other flavors (default/dark) also use a darker color? If the VS Code theme doesn't use any of the colors already defined in these variable, I think we should add a new variable for this and re-use it across the different themes. Does that make sense?

**Comment by kaicataldo** [comment]
This should be fixed by https://github.com/kaicataldo/material.vim/pull/21
