### ISSUE TITLE
Nvim creates problems while opening after the theme installation

### ISSUE THREAD

**Issue by nsoni** [kaicataldo/material.vim#2]
Hi, I am a little new to the vim world. I am trying to install this theme. I used `vim-plug` to install the theme and the theme was installed successfully. Here are my configurations for the theme:

```shell
Plug 'kaicataldo/material.vim'

syntax enable
set background=dark

if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  set termguicolors
endif

let g:material_theme_style = 'palenight'
let g:material_terminal_italics = 1
let g:airline_theme = 'material'
let g:lightline = { 'colorscheme': 'material_vim' }

colorscheme material
```

Now neovim throws an error when I open any file with this error:
```sh
Error detected while processing /Users/mac/.config/nvim/init.vim:
line   47:
E185: Cannot find color scheme 'material'
Press ENTER or type command to continue
```

not sure what am I missing here.

**Comment by kaicataldo** [comment]
Hey, apologies for just seeing this. Do you know which line the error is coming from? It looks like it's line 47, but it's not clear to me which line that corresponds to above. Here's [my setup](https://github.com/kaicataldo/dotfiles/blob/master/vim/.vimrc) (I also use NeoVim).

You shouldn't need both the airline and lightline themes to be specified - I would only specify whichever one you're using.

**Comment by kaicataldo** [comment]
Closing since there hasn’t been a response from the author.

**Comment by niloct** [comment]
I've just installed neovim on Windows 10 and had the same error.

What fixed it for me was setting the `call plug#end()` right after the last `Plug`, and **before** the `colorscheme material` declaration.

I'm attaching my `init.vim` (had to change the extension to .txt, please remove the extension).

[init.vim.txt](https://github.com/kaicataldo/material.vim/files/4737600/init.vim.txt)

**Comment by KeerthananPs** [comment]
You should move Your theme to nvim/runtime/colors directory then it solve the issue
