### ISSUE TITLE
Set the PMenu guibg to something more appropiate

### ISSUE THREAD

**Issue by nobobo1234** [kaicataldo/material.vim#23]
When using material.vim the background of my floating window is magenta on default. Maybe it's better to change this to something gray-ish?
![image](https://user-images.githubusercontent.com/14055571/60396344-9b772600-9b40-11e9-868e-a9e5d4b707d3.png)

**Comment by kaicataldo** [comment]
Oh yeah, that’s not great! I just did a rewrite and this is probably a regression.

**Comment by nobobo1234** [comment]
Great!

**Comment by kaicataldo** [comment]
This should be fixed by https://github.com/kaicataldo/material.vim/commit/533b80e1ba2293e391784b002b6d18053ef9eb17.

Please confirm if you get a chance!
