### ISSUE TITLE
vim airline can't resolve material theme

### ISSUE THREAD

**Issue by Goku-San** [kaicataldo/material.vim#26]
Hello, this is more of a question

Will you make the theme work with vim-airline again ?

Since the last update 4 days ago, airline can't find the theme

It worked before, no issues, both gVim and terminal vim

Thanks.

**Comment by kaicataldo** [comment]
Hey, I removed the airline theme in a recent rewrite. I'm not opposed to having it in here, as long as it matches the lightline theme. PRs are definitely welcome!

**Comment by Goku-San** [comment]
@kaicataldo can you send me the airline theme file?
I am beginner so I don't know how to write themes 
You can do it as separate repository. 
I really like your theme and can't find other, am so used to it
Thanks

**Comment by kaicataldo** [comment]
Sure thing - it’s in the Git history! This should be the commit before it was removed: https://github.com/kaicataldo/material.vim/blob/5aabe47c7a2086e54527732d283a7d2fe56b5cec/autoload/airline/themes/material.vim

Apologies for the inconvenience.

**Comment by Goku-San** [comment]
@kaicataldo Thanks again, it works now.
