### ISSUE TITLE
Italic font color

### ISSUE THREAD

**Issue by robechun** [kaicataldo/material.vim#27]
Hi--

just wanting to do a small configuration change so that the comments are lighter (whiter). Currently looks like this and is hard to see.

![image](https://user-images.githubusercontent.com/19492578/62192826-383d0700-b32b-11e9-83bc-792ff4fc4ee6.png)

What values would I need to change to make this work?

Thank you,

**Comment by kaicataldo** [comment]
You'll want to change [this line](https://github.com/kaicataldo/material.vim/blob/master/colors/material.vim#L200).

Closing because this question is answered.
