### ISSUE TITLE
Inline diffs not highlighted

### ISSUE THREAD

**Issue by ashwinvis** [kaicataldo/material.vim#28]
See the word ASDFGHJKL below compared with 2 color schemes

## seoul256

![Screenshot_20190804_185824](https://user-images.githubusercontent.com/9155111/62426802-11dfe880-b6ea-11e9-817d-b2e9a5b89c34.png)

## material.vim

![Screenshot_20190804_185745](https://user-images.githubusercontent.com/9155111/62426804-14dad900-b6ea-11e9-9e42-4c79220933cd.png)

**Comment by kaicataldo** [comment]
Thanks for the issue. What are you using to view the diff? vim-fugitive?

**Comment by kaicataldo** [comment]
This should be fixed. Thanks for the report!

<img width="1680" alt="Screen Shot 2019-08-04 at 1 49 40 PM" src="https://user-images.githubusercontent.com/7041728/62427282-bfd59d80-b6be-11e9-9429-281476f3e4f9.png">
