### ISSUE TITLE
Original color scheme

### ISSUE THREAD

**Issue by brokenpylons** [kaicataldo/material.vim#29]
Hi,

I really liked the old color scheme, would you consider making an "original" variant. The current default foreground color is way too bright...

**Comment by kaicataldo** [comment]
I'm not sure what you mean by "old color scheme". Mind clarifying for me?

**Comment by brokenpylons** [comment]
The colors were different when I first installed the theme about a year ago. Around commit 8677e8d29527df800d899be89ed373ea54556756.

**Comment by kaicataldo** [comment]
Thanks for explaining. I did do a major rewrite, but it was much later than the commit you linked to above (see  https://github.com/kaicataldo/material.vim/commit/8e388d90af434a5bd1ea1b4a5572352c187c5789). In this commit I went through and made the theme match the original VS Code theme much closer (which is the intention of this project!).

I don't think I can commit to maintaining a different variation that's not part of the original theme, but please feel free to create your own fork from before the rewrite and use that!
