### ISSUE TITLE
I am using vim version 7.4 and it's not working for me.

### ISSUE THREAD

**Issue by tapsu01** [kaicataldo/material.vim#3]

**Comment by kaicataldo** [comment]
Hi - can you provide more details about what isn't working?  If it's a visual thing, screenshots can be helpful.

**Comment by tapsu01** [comment]
![screenshot from 2018-06-11 12-03-47](https://user-images.githubusercontent.com/13838358/41215802-34ebd48c-6d7c-11e8-8dcd-c497e706d477.png)
This is vim information and my settings. Maybe I did wrong somewhere

**Comment by kaicataldo** [comment]
This theme currently relies on true colors being enabled - do you know if your terminal supports that? The directions for turning on true colors in your config are in the readme.

One follow up question - does vim-hybrid-material work with this setup? Might be an easy way to see if it’s a bug with this color scheme or something else that’s causing the colors not to apply correctly.

**Comment by tapsu01** [comment]
vim-hybrid-material works perfectly with this setup
![screenshot from 2018-06-11 23-14-29](https://user-images.githubusercontent.com/13838358/41243762-39bcc93e-6dcd-11e8-9740-33f91d13dc3f.png)

**Comment by kaicataldo** [comment]
Great, good to know. Did you try turning on true colors?

**Comment by tapsu01** [comment]
I encountered an error when setting up: let g:material_theme_style = 'default' | 'palenight' | 'dark'
![screenshot from 2018-06-12 23-51-44](https://user-images.githubusercontent.com/13838358/41304929-a629adc0-6e9b-11e8-8020-f2b3f96ae75e.png)

**Comment by kaicataldo** [comment]
Ah yeah - maybe the docs aren't clear enough, but I was trying to convey that it can be any one of those values, not that the value should be all of them.

`let g:material_theme_style = 'default' | 'palenight' | 'dark'` isn't valid.

Instead, it needs to be one of the following:
 - `let g:material_theme_style = 'default'` (this is the same as not setting it since it's the default)
 - `let g:material_theme_style = 'palenight'`
 - `let g:material_theme_style = 'dark'`

**Comment by kaicataldo** [comment]
And out of curiosity, was the issue with the colors before not turning on true colors?

**Comment by tapsu01** [comment]
I use vim version 7.4.1648 so it did not work and then I upgraded to vim 8

**Comment by tapsu01** [comment]
It seems the problem lies in my Vim version. I tried to turn on true colors but it did not work and I upgraded to Vim version 8. Everything was perfect. Thank you for supporting me.

**Comment by kaicataldo** [comment]
Got it! Glad it’s working for you! I’m going to close this since we resolved the issue, but feel free to make a new issue if you have any other questions.
