### ISSUE TITLE
Control sequence spitout with Kitty terminal

### ISSUE THREAD

**Issue by tsujp** [kaicataldo/material.vim#32]
I am getting control sequence dumps into my terminal stdin, I assume it's this plugin as my .vimrc is minimal and contains nothing special except for loading this plugin. I've checked that my TERM is set appropriately, `xterm-kitty` and this issue keeps cropping up. Does the following mean anything to the devs here?

Here's the issue I am referencing: https://github.com/kovidgoyal/kitty/issues/2018

**Comment by kaicataldo** [comment]
I'm a bit confused. In this issue you're linking, you say you're using https://github.com/hzchirs/vim-material. Can you confirm you're using this plugin?

**Comment by kaicataldo** [comment]
Closing this since there's been no response from the author. Feel free to make a new issue if you're still encountering a problem.
