### ISSUE TITLE
iterm colors not showing

### ISSUE THREAD

**Issue by rishabhdeepsingh** [kaicataldo/material.vim#33]
It's Showing the wrong colors. I am using iterm2.
<img width="1680" alt="Screenshot 2019-10-09 at 4 43 40 AM" src="https://user-images.githubusercontent.com/28526643/66440070-59b71f00-ea4f-11e9-9147-b176824dd624.png">

**Comment by kaicataldo** [comment]
Are you using [true colors](https://github.com/kaicataldo/material.vim#true-colors)?

**Comment by kaicataldo** [comment]
For what it's worth, I use iTerm2 and am not able to replicate this. If you are using true colors, can you share what version of Vim or Neovim you're using?

**Comment by rishabhdeepsingh** [comment]
Yes, I am using true colors. its in the `.vimrc` file as shown in the picture.
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  9 2019 04:09:55)
macOS version
Included patches: 1-2102
Compiled by Homebrew
```

**Comment by kaicataldo** [comment]
Your configuration for the theme looks correct to me, so it seems likely that it's something else in your configuration/setup.

**Comment by rishabhdeepsingh** [comment]
It worked but now the Comments are showing badly.
<img width="1680" alt="Screenshot 2019-10-12 at 10 42 12 AM" src="https://user-images.githubusercontent.com/28526643/66695251-00641f80-ecdd-11e9-9320-933f2f4778e1.png">

**Comment by rishabhdeepsingh** [comment]
I got it fixed by setting `set -g default-terminal "tmux-256color"` in my `.tmux.config` and this
```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```
in `.vimrc`

**Comment by kaicataldo** [comment]
Ah okay, so it was a tmux issue. Makes sense! Glad you figured it out.

**Comment by denvaar** [comment]
@rishabhdeepsingh to get italics to work, you need to set 
```
let &t_ZH="\<Esc>[3m"
let &t_ZR="\<Esc>[23m"
```
in your vimrc.
