### ISSUE TITLE
Increase the contrast of line numbers in palenight?

### ISSUE THREAD

**Issue by danilofreire** [kaicataldo/material.vim#34]
Thanks a lot for the great theme, it's by far my favourite one! 

I would like to ask you whether it's possible to increase the contrast of the line numbers in the palenight theme. They're sometimes a bit hard to read (or do I just need glasses? 😆). Is there any way to make the line numbers more visible? Thanks again! 😄

**Comment by kaicataldo** [comment]
Thanks for the kind words :) The goal of this project is to track the colors in https://github.com/material-theme/vsc-material-theme. If it's different from that, we should definitely make it match!

**Comment by danilofreire** [comment]
Thanks for the reply. Sorry if I'm asking for something that is a bit far from the goals of the project, I'm indeed the only person who asked for that 😄 . Feel free to close the issue if you don't think it's a good idea. Any help on how to change the contrast of the line numbers would be greatly appreciated!

**Comment by kaicataldo** [comment]
You should be able to fork it and modify [this line](https://github.com/kaicataldo/material.vim/blob/69df3a6f0ea2fbcb1025ca3106ba3b01a765b061/colors/material.vim#L85) 🙂

**Comment by danilofreire** [comment]
Done! 😉
