### ISSUE TITLE
NerdTree weird highlight

### ISSUE THREAD

**Issue by vkaracic** [kaicataldo/material.vim#37]
I pretty much have the same issue as described here: https://www.reddit.com/r/neovim/comments/ahcg9e/nerdtree_file_highlight/
with the default theme. 
Is this something theme related? Since it worked on my previous theme.

**Comment by kaicataldo** [comment]
Interesting. I'm only seeing this issue Neovim. Vim looks fine!

#### Vim
<img width="374" alt="Screen Shot 2019-12-06 at 12 24 51 AM" src="https://user-images.githubusercontent.com/7041728/70298219-dc91f700-17be-11ea-9eec-885280b83606.png">

#### Neovim
<img width="400" alt="Screen Shot 2019-12-06 at 12 24 55 AM" src="https://user-images.githubusercontent.com/7041728/70298229-e1ef4180-17be-11ea-9d62-df9fb1792287.png">
