### ISSUE TITLE
iTerm themes failing import.

### ISSUE THREAD

**Issue by reygarcia2009** [kaicataldo/material.vim#39]
I downloaded the iTerm palenight theme and tried importing within iTerm but am receiving the following error:

`The selected file could not be read or did not contain a valid color scheme`

**Comment by reygarcia2009** [comment]
Non-issue

**Comment by kaicataldo** [comment]
What was the problem, if you don't mind sharing? Might be useful to have here for posterity for future visitors :)

**Comment by reygarcia2009** [comment]
I tried just copying the contents into my own file but that wasn't working properly for some reason. I just saved the raw file and removed the .txt extension 👍

**Comment by kaicataldo** [comment]
Huh, interesting. Glad you got it working!
