### ISSUE TITLE
Matching parenthesis highlighting confusing (MatchParen)

### ISSUE THREAD

**Issue by klauer** [kaicataldo/material.vim#48]
This may just be me/my terminal/some misconfiguration, but I find matching parentheses very easy to confuse with the cursor. (neovim nightly, default theme style, alacritty / screen-256color)

Current settings `call s:SetHighlight('MatchParen', s:comments, s:cyan, 'bold')`
<img width="49" alt="image" src="https://user-images.githubusercontent.com/5139267/85472249-7015f400-b566-11ea-865a-1c3221d4e752.png">
(match parenthesis first, then cursor)

An arbitrary tweak on my end (that's not likely within the parameters of the original theme): `call s:SetHighlight('MatchParen', s:caret, s:bg, 'bold')` results in a bit more pleasing:
<img width="54" alt="image" src="https://user-images.githubusercontent.com/5139267/85473352-f4b54200-b567-11ea-80f3-910edd8f4509.png">
(match parenthesis first, then cursor)

For anyone else with the same issue, it's fortunately easy enough to fix on your own without modifying material.vim:
```vim
hi MatchParen cterm=bold ctermfg=220 gui=bold guifg=#ffcc00 guibg=#263238
```

**Comment by kaicataldo** [comment]
Sorry this fell through the cracks. Happy to take a look at a PR if you think we can find a better solution :) Ideally, would like to stay as close to the official Material theme as possible.

**Comment by cousine** [comment]
I believe @klauer solution fits the official theme; check [this line](https://github.com/material-theme/vsc-material-theme/blob/a1b2331583d3485cb82c4e9d6c55726a965aa770/scripts/generator/color-set.ts#L349).

changing [material.vim:173](https://github.com/kaicataldo/material.vim/blob/7dfa4bbf1fe43fcebcd836ef4f3b1342b4ea69be/colors/material.vim#L173) does the trick

**Comment by kaicataldo** [comment]
@cousine Awesome! Happy to review a PR :)
