### ISSUE TITLE
Poor HTML highlighting

### ISSUE THREAD

**Issue by lmlorca** [kaicataldo/material.vim#49]
![2020-07-23-15:43:30](https://user-images.githubusercontent.com/29153842/88293414-43870080-ccfb-11ea-84f0-0e974a741186.png)

Tags and their attributes are the same color. In the original vscode version, tags are red, and attributes are purple, but here I see everything in the same purple.

 I'm using the lastest neovim version. Tried disabling all plugins. My settings are pretty much default:

```
" True Color Support
if (has("termguicolors"))
 set termguicolors
endif

" Material Theme
let g:material_term1nal_italics = 1
let g:material_theme_style = 'darker'
colorscheme material
```

**Comment by lmlorca** [comment]
At the moment, I found that set syntax=javascript works as a workaround:

 
![2020-07-23-16:17:22](https://user-images.githubusercontent.com/29153842/88297317-0e30e180-cd00-11ea-8378-83313c28befd.png)

**Comment by kaicataldo** [comment]
PRs welcome to make the HTML syntax colors match the JavaScript syntax colors :)

**Comment by lmlorca** [comment]
Done. Now it should look more like Material Theme in vscode...

![2020-07-24-14:50:23](https://user-images.githubusercontent.com/29153842/88392902-19961280-cdbd-11ea-809f-7488d8b61e03.png)

**Comment by lmlorca** [comment]
https://github.com/kaicataldo/material.vim/pull/50

I updated the PR with more screenshots before/after, including the other theme variants aswell.

**Comment by kaicataldo** [comment]
Fixed by https://github.com/kaicataldo/material.vim/pull/51.
