### ISSUE TITLE
Keywords and comments with background highlighted

### ISSUE THREAD

**Issue by aeciolevy** [kaicataldo/material.vim#56]
Hi I tried material theme and I am getting javascript comments and some keywords with the background highlight.

![Screen Shot 2020-10-21 at 10 29 55 AM](https://user-images.githubusercontent.com/16165803/96735119-3a084580-1389-11eb-81e9-b70bcabe36db.png)

I am just wondering if someone else got this issue before. Is it normal?

**Comment by kaicataldo** [comment]
No, this isn't how it's supposed to look! It looks like it might be occurring with italicized text - do you have [that option](https://github.com/kaicataldo/material.vim#italics) turned on? 

I think I've seen this while using Vim in tmux before. Any chance you're using that? If not, it's either some kind of configuration or Vim version issue.

**Comment by kaicataldo** [comment]
Ah, I also have https://github.com/kaicataldo/dotfiles/blob/6f6f83fddf12b6736d7942e50e3144e23aaf2b30/vim/.vimrc#L294 in my vimrc - might be worth seeing if that fixes it :)

**Comment by aeciolevy** [comment]
I have done a test. When I am opening with MacVim it just works and looks great.
So I am wondering if I an issue with iTerm2. I am not sure if it uses `tmux` as terminal. I will look more into that.

```
if (has('termguicolors'))
  set termguicolors
endif
set t_Co=256
let g:material_terminal_italics = 1
let g:material_theme_style = 'darker'
colorscheme material
```

This is my setup:
macOS:10.15.7
terminal: iTerm2
vim: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 16 2020 05:34:50)

**Comment by aeciolevy** [comment]
So the fix you propose for italic solved everything, thanks!

```
" Fix italics in Vim
if !has('nvim')
  let &t_ZH="\e[3m"
  let &t_ZR="\e[23m"
endif
```

**Comment by kaicataldo** [comment]
Great! I'll add this to the readme. Cool if I close this?

**Comment by kaicataldo** [comment]
For posterity, here's another report of this issue for another theme: https://github.com/joshdick/onedark.vim/issues/61

**Comment by aeciolevy** [comment]
Thanks for the help. You can close.
