### ISSUE TITLE
Mention vim-javascript in README

### ISSUE THREAD

**Issue by kgehmlich** [kaicataldo/material.vim#57]
It took me quite a while to come across the [vim-javascript](https://github.com/pangloss/vim-javascript) plugin. Until finding it, I thought this colour scheme was seriously lacking.

It would be great for other newcomers who use JavaScript if the README mentioned that the vim-javascript plugin would greatly improve their experience (along with any other plugins that improve this colour scheme's syntax highlighting).

Once that's installed, this plugin is fantastic! Thanks for taking the time!

**Comment by kaicataldo** [comment]
Ideally, this would be as generic as possible, but the built in JS syntax highlighting is quite simple, hence it not looking like the source theme. A note in the readme about this is fine by me! Would you like to make a PR?

**Comment by kgehmlich** [comment]
> Would you like to make a PR?

Can do! I wasn't sure if it was something you'd prefer to cover yourself, but I'm happy to do it.

**Comment by kgehmlich** [comment]
> the built in JS syntax highlighting is quite simple, hence it not looking like the source theme.

Certainly not your fault :)  The integration with vim-javascript solves that problem very nicely, imo.
