### ISSUE TITLE
treesitter support

### ISSUE THREAD

**Issue by kutsan** [kaicataldo/material.vim#59]
- https://github.com/nvim-treesitter/nvim-treesitter
- https://github.com/rockerBOO/awesome-neovim#treesitter-support

**Comment by kaicataldo** [comment]
I’m open to this as long as it’s done in a backwards-compatible way!

**Comment by kutsan** [comment]
I guess linking the highlight groups does the job?

https://github.com/mhartington/oceanic-next/blob/29d694b9f6323c90fb0f3f54239090370caa99fb/colors/OceanicNext.vim#L150-L168

**Comment by kaicataldo** [comment]
Yes! If we know the highlight group name it can easily be added to the current colorscheme. PRs welcome!

**Comment by kutsan** [comment]
With https://github.com/kaicataldo/material.vim/pull/64 merged, I think we can close this issue.
