### ISSUE TITLE
I am using vim 8.0 and iterm2 3.1.6 and it is not working for me.

### ISSUE THREAD

**Issue by rhisling** [kaicataldo/material.vim#6]
<img width="1140" alt="screen shot 2018-06-23 at 3 10 43 am" src="https://user-images.githubusercontent.com/35667987/41808509-46fcbcde-7693-11e8-85d7-5c82822c007d.png">

**Comment by rhisling** [comment]
Truecolors are also enabled but still I am getting the fallback colors :(

**Comment by kaicataldo** [comment]
What version of Vim are you using?

Edit: Sorry, I noticed you mentioned this in the issue title.

**Comment by kaicataldo** [comment]
Actually, I'm seeing the same thing when I use Vim (I use NeoVim these days, so I hadn't noticed it). I'll try to find some time to dig into this, but please feel free to take a look if you can!

**Comment by rhisling** [comment]
It works flawlessly on NeoVim and MacVim. Thanks for the beautiful theme  :) On a side note, quantum also doesn't seem to work but palenight works fine in vim.

**Comment by kaicataldo** [comment]
Ah, that makes sense. Thanks for looking into this! I'm a bit swamped right now, but I'll try to get to fixing this sometime soon!

**Comment by kaicataldo** [comment]
It seems like the reason the version based on palenight works is because it uses the `cterm` values for everything - it's still not using true colors 😭. Will keep digging.

**Comment by kaicataldo** [comment]
@rhisling I just updated to Vim 8.1 and it seems to be working correctly for me now. Could you try the latest release and see if it's fixed for you too?

**Comment by kaicataldo** [comment]
Closing this since it appears to be working with the latest version of Vim and there hasn't been a response from the issue author. Please feel free to open a new issue if you continue experiencing any problems!

**Comment by parmort** [comment]
After looking through the [vim 8 changelog](http://ftp.vim.org/pub/vim/patches/8.0/) and the commit history, I think that patch `755` (8.0.0755) possibly solved the issue.
