### ISSUE TITLE
Add Lualine theme

### ISSUE THREAD

**Issue by eaxly** [kaicataldo/material.vim#62]
[Lualine](https://github.com/hoob3rt/lualine.nvim) has it's own material theme but – similiar to the builtin lightline theme – it does not sync with the style of the vim theme.  
Would it be possible to add it?

Thank you for this awesome vim theme and your time put into it! :D

**Comment by kaicataldo** [comment]
Thanks for the kind words! I'm absolutely open to including a Lualine theme, but I unfortunately don't currently have the time to dig into it myself. PR would be welcome!

**Comment by Fymyte** [comment]
I recently switched to lualine, but couldn't find my favorite theme.
I created a pr with a theme for it. I used colors from lightline as base.
