### ISSUE TITLE
copy material.vim to colorschemes folder?

### ISSUE THREAD

**Issue by mrwonderfulness** [kaicataldo/material.vim#66]
will vim-plug automatically copy the material.vim file to the colorschemes directory, or does need to be done manually? 

without moving the material.vim file i get this:

`E185: Cannot find color scheme 'material'`

**Comment by kaicataldo** [comment]
Yeah, it should just work, assuming you followed the instructions in the readme. Maybe try reinstalling? If that doesn't work, any other relevant info you can share? I haven't run into this before.

**Comment by BlueWhaleYT** [comment]
I had this problem like you. I solved this by typing `:PlugInstall` in vim editor and it started installing. Hope that helps.

**Comment by kaicataldo** [comment]
Closing since this doesn't appear to be a problem with the plugin itself. Please feel free to open a new issue if you're still having any problems. Thanks!
