### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by Goku-San** [kaicataldo/material.vim#70]
Hello,
I just updated and got this error. I use vim 9.0.0910. I tried to debug and the problem is in this file, the work that you did yesterday :) https://github.com/kaicataldo/material.vim/commit/05efa0cc016984d7cecd4c54ac9fb4a612132067

I solved it by adding if condition after L563 ``" Tree-sitter`` , upto L591.
```vim
if has('nvim')
...
endif
``` 
I don't know how to ask if it has tree-sitter :D 

Found possible other solutions, but I don't know how to implement them.
[elixir issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1405) on nvim-treesiter repo and among the comments I found [this](https://github.com/theHamsta/nvim-treesitter/commit/346aeafca06ef7a6719da566a34312340d32b777)

If you could be kind enough to implement at least the if statement :)

Thanks.

**Comment by kaicataldo** [comment]
Thanks for the report. I don't have time to fix this myself right now, but I'll go ahead and revert that last PR and ask the author to revisit if they'd still like to work on it.
