### ISSUE TITLE
All identifiers are red in ts files

### ISSUE THREAD

**Issue by Andrii-Vovk** [kaicataldo/material.vim#74]
Hey! I just installed this theme, and for some reason it makes all the identifiers in .ts files red. Is there a way to change that? I'm really used to them being white in vscode's material theme

![image](https://github.com/kaicataldo/material.vim/assets/61578830/458bc147-701f-4cbb-aa0c-e320888df21e)

I'm using lunarvim; Here is my config:

```lua
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  { command = "eslint", filetypes = { "typescript", "typescriptreact", "javascript", "javascriptreact" } }
}

local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  {
    command = "prettier",
    filetypes = { "typescript", "typescriptreact", "javascriptreact", "javascriptreact" },
  },
}

require("lvim.lsp.manager").setup "tailwindcss"

local code_actions = require "lvim.lsp.null-ls.code_actions"
code_actions.setup {
  {
    exe = "eslint",
    filetypes = { "typescript", "typescriptreact", "javascript", "javascriptreact", "vue" },
  },
}

lvim.format_on_save.enabled = true

lvim.lsp.buffer_mappings.normal_mode['H'] = { vim.lsp.buf.hover, "Show documentation" }
lvim.keys.normal_mode["gD"] = "<cmd>lua vim.lsp.buf.declaration()<CR>"

lvim.colorscheme = "material"

lvim.plugins = {
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    event = "InsertEnter",
  },
  {
    "zbirenbaum/copilot-cmp",
    after = { "copilot.lua" },
    config = function()
      require("copilot_cmp").setup()
    end,
  },
  {
    "kaicataldo/material.vim",
    config = function()
      vim.g.material_theme_style = "default-community"
      vim.g.material_terminal_italics = true
    end,
  },
}

local ok, copilot = pcall(require, "copilot")
if not ok then
  return
end

copilot.setup {
  suggestion = {
    keymap = {
      accept = "<c-l>",
      next = "<c-j>",
      prev = "<c-k>",
      dismiss = "<c-h>",
    },
  },
}

local opts = { noremap = true, silent = true }
vim.api.nvim_set_keymap("n", "<c-s>", "<cmd>lua require('copilot.suggestion').toggle_auto_trigger()<CR>", opts)```

Appreciate any help!

**Comment by Andrii-Vovk** [comment]
Fixed this for now with an autocommand:
`"ColorScheme", {
    pattern = "*",
    callback = function()
        vim.cmd("highlight Identifier ctermfg=White guifg=White")
    end
}`

But it seems like a workaround, please let me know, if there is a proper solution

**Comment by kaicataldo** [comment]
Hiya! Do you know which TypeScript syntax highlighting plugin you're using? Here's what I see using my setup (using [HerringtonDarkholme/yats.vim](https://github.com/HerringtonDarkholme/yats.vim)):
<img width="251" alt="Screenshot 2024-01-19 at 7 05 45 PM" src="https://github.com/kaicataldo/material.vim/assets/7041728/6562279a-dfe3-4c2c-803a-a4c9f6f6b60d">

 It's possible that the syntax highlighting plugin you're using is setting those values, so would be good to track down the root cause of the issue. Thanks!

**Comment by Andrii-Vovk** [comment]
Hey! Lunarvim uses nvim-treesitter by default. 
I tried disabling all the plugins that i added on top, and the issue persisted, so it seems that its an issue with treesitter?  I'm pretty new to vim, so i'm not sure what are my next steps here, and this seems already out of scope here, as this is not a problem with your theme, but I would appreciate any help!
Thanks!

**Comment by cpmsmith** [comment]
@Andrii-Vovk I expect you're getting those highlights from the TypeScript language server, not from tree-sitter. You can confirm that, as well as what highlight group it's using, by running the `:Inspect` ex command with your cursor on one of the symbols that's getting highlighted. For whatever reason, it looks like `@lsp.type.variable` links to `Identifier`, even though `@variable` doesn't.

<img width="606" alt="image" src="https://github.com/kaicataldo/material.vim/assets/9437625/54d41df5-89fb-4424-8807-ee6f2aa92e17">

You can disable highlights from the language server as described [here](https://old.reddit.com/r/neovim/comments/109vgtl/how_to_disable_highlight_from_lsp/), by removing `semanticTokensProvider` from the `server_capabilities`. Judging from [the LunarVim docs](https://www.lunarvim.org/docs/configuration/language-features/language-servers#by-overriding-the-setup), I think that would look like this:

```lua
local default_on_init = require("lvim.lsp").common_on_init
require("lvim.lsp.manager").setup("tsserver", {
  on_init = function (client)
    client.server_capabilities.semanticTokensProvider = nil
    default_on_init(client)
  end,
})
```

Or, if you want to keep the LSP-based highlighting, you can just unlink the one group as described in the Neovim docs:
https://github.com/neovim/neovim/blob/32b49448b227588c2fbc93f89743104fd445e0a6/runtime/doc/lsp.txt#L470

**Comment by Andrii-Vovk** [comment]
Thank you, I really appreciate your help!

**Comment by kaicataldo** [comment]
@cpmsmith Thanks for digging into this!
