### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by seriiserii825** [kaicataldo/material.vim#8]
I install with vundle.
http://joxi.ru/D2Pj8Oqtp664Kr
What may be the problem?

**Comment by parmort** [comment]
What Vim version are you using (find with `:version`)? You want at least vim `8.0` with patches up to 755 and at best any version of vim `8.1`.

Edit: With patch 755 the way vim interprets GUI-based colorschemes changed slightly.

**Comment by kaicataldo** [comment]
Hi - knowing what version of Vim/NeoVim you're using would be great. Thanks!

**Comment by kaicataldo** [comment]
Closing this since there hasn't been a response from the issue creator in quite a while. Feel free to make a new issue if this is still a problem.
