### ISSUE TITLE
dark and palenight don't work

### ISSUE THREAD

**Issue by Keris** [kaicataldo/material.vim#9]
Hello, I am using vim 8.1 on macOS, the default works fine, but the other theme styles don't work.

```
" set color scheme
set background=dark
colorscheme material

" Enable true colors
if (has("termguicolors"))
  set termguicolors
endif

let g:material_theme_style = 'palenight'
let g:material_terminal_italics = 1
```
Above settings make a default display.

<img width="568" alt="screen shot 2018-08-21 at 10 06 38 pm" src="https://user-images.githubusercontent.com/4636489/44406588-95163600-a58e-11e8-91d8-2794c350fe1b.png">

**Comment by kaicataldo** [comment]
Hey there, thanks for the issue. The settings variables need to be set before `colorscheme`. Can you let me know if it works with the following order?

```
" Enable true colors
if (has("termguicolors"))
  set termguicolors
endif

" material theme settings
let g:material_theme_style = 'palenight'
let g:material_terminal_italics = 1

" set color scheme
set background=dark
colorscheme material
```

**Comment by Keris** [comment]
Hi, I changed the settings using your suggested order, it works but the comment line is highlighted.
<img width="634" alt="screen shot 2018-08-22 at 11 11 19 am" src="https://user-images.githubusercontent.com/4636489/44440849-94b48400-a5fc-11e8-8010-a9cbeac33884.png">

**Comment by Keris** [comment]
The comment line problem is caused by italics setting, after I disabled it, everything is ok. I don't need italics too much, so it does not matter.

**Comment by kaicataldo** [comment]
I had to add this section to my .vimrc to get italics working in Vim: https://github.com/kaicataldo/dotfiles/blob/master/vim/.vimrc
